# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06b175e7eeb3aeffc6741575a255499a03d970db7f06aba1d695b06ba402a3864ac233938550408b33c2f44d7f36921127f461d71fa188b1c2eb01d7713278f8

test:
  secret_key_base: a0b83573eb29b2d596c3ac2031662a489c79834dc13b279408afc59fc49b49f20cd79c2de29a97e6bfbd454c3ba38edf14d91593e66190a49881968acf81e4de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
